---
title: "The exploration's report"
date: "September, 2019"
---

```{r setup_exploration, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos =  "h")
knitr::opts_knit$set(root.dir = "../")

# libraries for markdown
library(rmarkdown)
library(knitr)

# libraries for data prep
library(dplyr)
library(stringr)

# libraries for spatial data manipulation
library(spatialreg)
library(maps)
library(maptools)    
library(rgdal)     
library(sp)  
library(spdep)
library(bamlss)
library(gstat)
library(splancs)
library(spatstat)
library(pgirmess)
library(classInt)
library(spgwr)

# libraries for plots and visualization
library(RColorBrewer)
library(tmap)
library(ggplot2)
library(ggExtra)

# libraries for modeling
library(MASS)
```

# Loading the processed data

After perform data preparation, we can load the processed data using the following code.

```{r data_loading, echo=TRUE, out.width = '100%'}
# performing data (processed) loading
dataRawDirectory <- "./data/processed/"
shapefile_to_read <- paste(dataRawDirectory, "crime_mg_processed.shp", sep = "")
target <- readOGR(shapefile_to_read, encoding="UTF-8")
```

# Initial exploration

Then, we can get an initial exploration on the data and the shapefile.

```{r initial_exploration, echo=TRUE, out.width = '100%'}
summary(target@data)
plot(target)
names(target)
```


